"""Create all

Revision ID: 26fa1fa9d3e9
Revises: 
Create Date: 2023-12-15 19:52:59.604814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26fa1fa9d3e9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('respondents',
    sa.Column('respondent', sa.Integer(), nullable=True),
    sa.Column('sex', sa.Enum('M', 'W', name='sex'), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_respondents_id'), 'respondents', ['id'], unique=False)
    op.create_index(op.f('ix_respondents_respondent'), 'respondents', ['respondent'], unique=True)
    op.create_table('weights',
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('respondent', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['respondent'], ['respondents.respondent'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weights_date'), 'weights', ['date'], unique=False)
    op.create_index(op.f('ix_weights_id'), 'weights', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weights_id'), table_name='weights')
    op.drop_index(op.f('ix_weights_date'), table_name='weights')
    op.drop_table('weights')
    op.drop_index(op.f('ix_respondents_respondent'), table_name='respondents')
    op.drop_index(op.f('ix_respondents_id'), table_name='respondents')
    op.drop_table('respondents')
    # ### end Alembic commands ###
